language: ruby
cache: bundler
rbenv:
  - 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - gem update --system
  - gem install bundler:2.0.2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec
deploy:
  provider: heroku
